apiVersion: v1
kind: ServiceAccount
metadata:
  name: mbrokerbench-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-scaler
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mbrokerbench-scaler-binding
subjects:
  - kind: ServiceAccount
    name: mbrokerbench-controller
roleRef:
  kind: Role
  name: deployment-scaler
  apiGroup: rbac.authorization.k8s.io
