<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>12.0</LangVersion>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <StartupObject>MBrokerBench.BrokerSimulator</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="simulation_config.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
    <Content Include="simulation_config.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="2.13.1" />
    <PackageReference Include="ConsolePlot" Version="0.1.0" />
    <PackageReference Include="KubernetesClient" Version="19.0.2" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    <PackageReference Include="prometheus-net" Version="8.2.1" />
    <PackageReference Include="prometheus-net.AspNetCore" Version="8.2.1" />
    <PackageReference Include="Spectre.Console" Version="0.54.1-alpha.0.32" />
    <PackageReference Include="Terminal.Gui" Version="1.19.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="export_csv\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MSodaClient\MSodaClient.csproj" />
  </ItemGroup>

</Project>
